name: flutter_app_start
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast:
  mongo_dart:
  dbcrypt:
  shared_preferences:
  path_provider:


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/Other/imageSliderImage3.png
    - assets/Other/logo.png


    - assets/Other/dashboard.png
    - assets/Other/brinjalsIcon.png
    - assets/Other/pumpkinIcon.png
    - assets/Other/carrotIcon.png
    - assets/Other/mangoIcon.png
    - assets/Other/appleIcon.png
    - assets/Other/pineappleIcon.png
    - assets/Other/login.png
    - assets/Other/signup.png
    - assets/Other/about.png
    - assets/Other/correctIcon.gif
    - assets/Other/pointRight.gif

    - assets/Calender Icons/01.png
    - assets/Calender Icons/02.png
    - assets/Calender Icons/03.png
    - assets/Calender Icons/04.png
    - assets/Calender Icons/05.png
    - assets/Calender Icons/06.png
    - assets/Calender Icons/07.png
    - assets/Calender Icons/08.png
    - assets/Calender Icons/09.png
    - assets/Calender Icons/10.png
    - assets/Calender Icons/11.png
    - assets/Calender Icons/12.png
    - assets/Calender Icons/13.png
    - assets/Calender Icons/14.png
    - assets/Calender Icons/15.png
    - assets/Calender Icons/16.png
    - assets/Calender Icons/17.png
    - assets/Calender Icons/18.png
    - assets/Calender Icons/19.png
    - assets/Calender Icons/20.png
    - assets/Calender Icons/21.png
    - assets/Calender Icons/22.png
    - assets/Calender Icons/23.png
    - assets/Calender Icons/24.png
    - assets/Calender Icons/25.png
    - assets/Calender Icons/26.png
    - assets/Calender Icons/27.png
    - assets/Calender Icons/28.png
    - assets/Calender Icons/29.png
    - assets/Calender Icons/30.png
    - assets/Calender Icons/31.png


    - assets/Items/beans.png
    - assets/Items/carrot.png
    - assets/Items/leeks.png
    - assets/Items/knolkhol.jpg
    - assets/Items/cabbage.png
    - assets/Items/tomato.png
    - assets/Items/ladiesfingers.png
    - assets/Items/brinjals.png
    - assets/Items/pumpkin.png
    - assets/Items/cucumber.png
    - assets/Items/bittergourd.png
    - assets/Items/greenchilies.jpg
    - assets/Items/beetroot.png
    - assets/Items/potato.png


    - assets/Items/mango.jpg
    - assets/Items/lime.jpg
    - assets/Items/avocado.jpg
    - assets/Items/papaya.png
    - assets/Items/pineapple.jpg
    - assets/Items/banana.jpg


    - assets/App Screenshots/homepage.JPG
    - assets/App Screenshots/dashboardpage.JPG
    - assets/App Screenshots/vegetablespage.JPG
    - assets/App Screenshots/fruitspage.JPG
    - assets/App Screenshots/loginpage.JPG
    - assets/App Screenshots/signuppage.JPG


    - assets/text.txt
















      # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
